[package]
name = "solitaire"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"

[features]
default = ["dynamic_linking"]
dynamic_linking = ["bevy/dynamic_linking"]

[profile.dev.package."*"]
opt-level = 3
