use cache_bust::asset;

use super::{Card, Suit, Value};

pub fn asset_name(card: Card) -> &'static str {
	use Value::*;
	use Suit::*;
	match (card.value, card.suit) {
		(Ace, Spades) => asset!("AS.svg"),
		(Two, Spades) => asset!("2S.svg"),
		(Three, Spades) => asset!("3S.svg"),
		(Four, Spades) => asset!("4S.svg"),
		(Five, Spades) => asset!("5S.svg"),
		(Six, Spades) => asset!("6S.svg"),
		(Seven, Spades) => asset!("7S.svg"),
		(Eight, Spades) => asset!("8S.svg"),
		(Nine, Spades) => asset!("9S.svg"),
		(Ten, Spades) => asset!("TS.svg"),
		(Jack, Spades) => asset!("JS.svg"),
		(Queen, Spades) => asset!("QS.svg"),
		(King, Spades) => asset!("KS.svg"),
		(Ace, Clubs) => asset!("AC.svg"),
		(Two, Clubs) => asset!("2C.svg"),
		(Three, Clubs) => asset!("3C.svg"),
		(Four, Clubs) => asset!("4C.svg"),
		(Five, Clubs) => asset!("5C.svg"),
		(Six, Clubs) => asset!("6C.svg"),
		(Seven, Clubs) => asset!("7C.svg"),
		(Eight, Clubs) => asset!("8C.svg"),
		(Nine, Clubs) => asset!("9C.svg"),
		(Ten, Clubs) => asset!("TC.svg"),
		(Jack, Clubs) => asset!("JC.svg"),
		(Queen, Clubs) => asset!("QC.svg"),
		(King, Clubs) => asset!("KC.svg"),
		(Ace, Diamonds) => asset!("AD.svg"),
		(Two, Diamonds) => asset!("2D.svg"),
		(Three, Diamonds) => asset!("3D.svg"),
		(Four, Diamonds) => asset!("4D.svg"),
		(Five, Diamonds) => asset!("5D.svg"),
		(Six, Diamonds) => asset!("6D.svg"),
		(Seven, Diamonds) => asset!("7D.svg"),
		(Eight, Diamonds) => asset!("8D.svg"),
		(Nine, Diamonds) => asset!("9D.svg"),
		(Ten, Diamonds) => asset!("TD.svg"),
		(Jack, Diamonds) => asset!("JD.svg"),
		(Queen, Diamonds) => asset!("QD.svg"),
		(King, Diamonds) => asset!("KD.svg"),
		(Ace, Hearts) => asset!("AH.svg"),
		(Two, Hearts) => asset!("2H.svg"),
		(Three, Hearts) => asset!("3H.svg"),
		(Four, Hearts) => asset!("4H.svg"),
		(Five, Hearts) => asset!("5H.svg"),
		(Six, Hearts) => asset!("6H.svg"),
		(Seven, Hearts) => asset!("7H.svg"),
		(Eight, Hearts) => asset!("8H.svg"),
		(Nine, Hearts) => asset!("9H.svg"),
		(Ten, Hearts) => asset!("TH.svg"),
		(Jack, Hearts) => asset!("JH.svg"),
		(Queen, Hearts) => asset!("QH.svg"),
		(King, Hearts) => asset!("KH.svg"),
	}
}
